server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/snack?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Sweetime010!
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orderManagement
          destination: test
          contentType: application/json
        event-out:
          destination: test
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8082
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: orderManagement
          destination: test
          contentType: application/json
        event-out:
          destination: test
          contentType: application/json


#kafka:
#  bootstrap:
#    address: http://localhost:9092
#  topic: eventTopic
#  consumer:
#    groupId: eventTopic-orderManagement
#  event:
#    location: com.example.eventTopic.kafka.event